name: xml_crypto
version: 3.0.1
description: |
  Xml digital signature library for Dart. For signing and verifying XML documents.
homepage: https://github.com/rikulo/xml-crypto
repository: https://github.com/rikulo/xml-crypto
issue_tracker: https://github.com/rikulo/xml-crypto/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.2.2
  xpath_selector: ^3.0.2
  xpath_selector_xml_parser: ^3.0.1
  crypto: ^3.0.2
  rsa_pkcs: ^2.0.1
  ninja: ^3.0.8

dev_dependencies:
  lints: ^2.0.0
  test: ^1.20.1

false_secrets:
  - /example/client.pem
  - /test/static/client.pem