name: xml_crypto
version: 2.1.3
description: Xml digital signature and encryption library for Dart
homepage: https://github.com/rikulo/xml-crypto
repository: https://github.com/rikulo/xml-crypto
issue_tracker: https://github.com/rikulo/xml-crypto/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^5.3.1
  xpath_selector: ^2.2.4
  crypto: ^3.0.1
  rsa_pkcs: ^2.0.1
  ninja: ^3.0.7

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1