name: xml_crypto
version: 5.0.0
description: |
  Xml digital signature library for Dart. For signing and verifying XML documents.
homepage: https://github.com/rikulo/xml-crypto
repository: https://github.com/rikulo/xml-crypto
issue_tracker: https://github.com/rikulo/xml-crypto/issues

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  xml: ^7.0.1
  crypto: ^3.0.7
  rsa_pkcs: ^2.1.0
  ninja: ^3.0.8

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0

false_secrets:
  - /example/client.pem
  - /test/static/client.pem